### ISSUE TITLE
Advanced Live Telemetry

### ISSUE THREAD

**Issue by christianuhlmann** [Ezka77/xen-orchestra-ce#25]
Hello everybody,

has anyone got the new feature "Advanced Live Telemetry" up and running?

https://xen-orchestra.com/blog/xen-orchestra-advanced-telemetry/
https://github.com/vatesfr/xen-orchestra/pull/4680

Christian

**Comment by Ezka77** [comment]
Not using it, but it requires the XCP-ng server to be available.

**Comment by jmccoy555** [comment]
Only via the manual install and then manually going to ip:19999

https://xcp-ng.org/forum/topic/2288/netdata-package-is-now-available-in-xcp-ng/2

Don't the the plugin is available.

**Comment by Ezka77** [comment]
humm the port 19999 from docker is not exposed by default, try to expose this port with the docker-compose file and let me know if something is missing.

**Comment by jmccoy555** [comment]
Its port 19999 on the xcp-NG host(s), not on XO. 

You need to install netdata on each host.

**Comment by Ezka77** [comment]
So is that an issue with the container ? or a configuration mismatch ? or something else ? 😕

**Comment by magikmw** [comment]
It's a money issue. The nescessary plugin is only available to Premium XOA users.  
See: https://xcp-ng.org/forum/post/19972 and two posts below that.

**Comment by olivierlambert** [comment]
It's not money, it's an extra service we provide outside the exact scope of Xen Orchestra, integrated to XOA (like XO Hub or recipes we created and hosted on our infrastructure).

You can **always** achieve the same result if you install Netdata in your hosts and configure it to stream metrics to another central Netdata, on your XO VM directly, or somewhere else.

This is a turnkey integration we provide for businesses. You can get the same "final product" by yourself, learning how Netdata it works (worth it in you are a "home" user)

I don't think this repo objective is to provide something else than Xen Orchestra itself (but I might be wrong).

**Comment by jmccoy555** [comment]
@magikmw the plugin just give you a proxy to access all your hosts by pressing the _Advanced Live Telemetry_ button on the Advance tab - https://xcp-ng.org/forum/topic/2859/netdata-plugin-open-or-closed-source/11?_=1589269604966

Just ssh into each host and `yum install netdata-ui` and go to http://host_address:19999;

> Installing Netdata manually
> If you want to do it your way, no problem 🙂 Just run yum install netdata-ui on each host you want to monitor and that's it. You can just go on http://host_address:19999 and enjoy all the metrics.

I guess it could possible do is make the Button work somehow by editing XO and adding a proxy that you could configure with the host ips in the docker config, but I guess that's quite a bit of (unnecessary) work!

**Comment by magikmw** [comment]
Ok, I'm sorry if I used an ambigious speech shortcut in the previous comment. I feel like I owe an explanation.  
By saying 'money' I ment "Advanced Live Telemetry" feature, as advertised, does not work for this particular deployment method of XO unless you use the paid, or business-dedicated version of XO. It doesn't because the plugin isn't there, you can't install it. Hence money makes the difference.

Yes netdata by itself is open source with a free licence and it can be used and set up however one sees fit, using the netdata-ui, grafana, a homebrew ncurses terminal dashboard, or even a line printer if one so desires. It's cool. It doesn't apply to this repo or running the "Advanced Live Telemetry" in a community build of XO. Because it's behind a paywall, which this solution directly works around (with the license's permission, and as I gather the creator's blessing).

And it's ok. No judgement or regret on my part @olivierlambert.  
It's also the end of OP's issue, since there's nothing to be done that's in scope of this repo (unless @Ezka77 sees it in a different way, obviously).  
I have no stake in this, anyway. Just saw the issue, did some research and wanted to help with the confusion, however misguided my method was.

@jmccoy555 Thanks. I saw that in the thread I linked, and already set it up for myself. I never heard of netdata before, but it seems like I might even bring it to my current business endeavour for evaluation.

**Comment by Ezka77** [comment]
Ok if it's not an issue from this repo, I'll close this. For any functionality, configuration or application you need for your usage, if it is not to complex and as far as this doesn't become a required dependency outside the one needed by XOA, I'll be happy to review and approve any merge request.
