### ISSUE TITLE
Build/Run with nodejs > 6 on Alpine

### ISSUE THREAD

**Issue by Ezka77** [Ezka77/xen-orchestra-ce#3]
With a node:8-alpine the image manage to build, but a segmentation fault occur at start time.
Tried to run some `strace` and `gdb` to look the backtrace but ... no clue when it appends.
Looked around on Segfault about NodeJS and Alpine : there is a lot of case where a segfault is raised none looks like mine, found some dirty hacks, tried some but no success.

Seems that NodeJS/npm/yarn now compile plugin source repos ... which, I guess, leads to some ABI incompatibility on some Gnu/Linux. I'll look further when I manage to get time, hopefully NodeJS/Alpine people will find a reliable way to get things working.

**Comment by christianuhlmann** [comment]
hi,

with xen-orchestra update to 5.20 (https://xen-orchestra.com/blog/xen-orchestra-5-20/) you should investigate in this issue because yarn 1.7.0 is needed an only the latest node:alpine image has yarn 1.7.0

> Cloning into 'xen-orchestra'...
Removing intermediate container 7a6e2f0417fb
 ---> 3b6b94de9297
Step 6/20 : RUN cd /home/node/xen-orchestra &&    yarn && yarn build
 ---> Running in c8e0965313c7
yarn install v1.6.0
[1/5] Validating package.json...
error @: The engine "yarn" is incompatible with this module. Expected version "^1.7.0".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command '/bin/sh -c cd /home/node/xen-orchestra &&    yarn && yarn build' returned a non-zero code: 1

i have cloned https://github.com/nodejs/docker-node/tree/master/6/alpine and change yarn Version String in the Dockerfile to 1.7.0 and build my own node:6-alpine.

with these node image the build of xo-ce did not stop and i can update to 5.20.
i have created a PR to the node repo (https://github.com/nodejs/docker-node/pull/770)

**Comment by Ezka77** [comment]
Hi, yeah with node 6 the yarn version mismatch ; and with a node > 6 the build is still failing on `leveldown` package build.  I'll look into it asap (next week I hope) ; I'll use your PR to build the 5.20 and if I found any solution to build `leveldb` I think to consider to use a Debian base NodeJS image.

**Comment by Ezka77** [comment]
The build goes fine with the nodejs 8 version. Cannot be build with 10 but it's an issue from Xen-Orchestra dependency.
