### ISSUE TITLE
CE Banners

### ISSUE THREAD

**Issue by xraver** [Ezka77/xen-orchestra-ce#31]
Hi 
With the latest version 5.59 at the login time and in the top of the page there are banners related to the community edition (This version is not bundled with any support nor updates. Use it with caution.).
It would be possible to remove them?? In version 5.58 there were not present. 

Thanks!!

**Comment by Ezka77** [comment]
Hi @xraver,

Well the banner is from the **CE version** of Xen Orchestra and before 5.59 a patch was applied (I thought that it wasn't used from months ... and I see now that quilt was using it anyway).

Out of the scope of this [issue](https://github.com/Ezka77/xen-orchestra-ce/issues/30#issuecomment-628712947), Olivier Lambert from XOA team answer this question. I think it's fair to leave this banner as you can close it and it's a reminder that this version is the CE. But if a majority think otherwise, I may re-use the patch. Let me know here why it bother you so much.

**Comment by xraver** [comment]
Hi thanks for your clarification.
I personally don't like the banner. i think is implicit in the usage of
this version (community edition) that you have explicitly indicated in the
name of your project.
In any case thanks for your work. I very appreciate your container.

Il giorno lun 18 mag 2020 alle ore 08:26 Ezka <notifications@github.com> ha
scritto:

**Comment by olivierlambert** [comment]
@xraver why not closing it, then?

Also, we'll probably add a cookie so it won't come just after a refresh. Does it sound reasonable to you?

**Comment by xraver** [comment]
> @xraver why not closing it, then?
> 
> Also, we'll probably add a cookie so it won't come just after a refresh. Does it sound reasonable to you?

Hi, i've closed the issue after my previouse replay.
i think is reasonable.
