### ISSUE TITLE
ARM Edition

### ISSUE THREAD

**Issue by DustyArmstrong** [Ezka77/xen-orchestra-ce#42]
Hi, 

Thanks for this project. 

Firstly I've built an arm version of this with alpine, do you mind if I fork?

Secondly - I am quite new to Dockerfiles, maybe I did something wrong, but when I try to run the container I get an error `/bin/remco: line 1: syntax error: unterminated quoted string`. I assume it's an error with a config file, but I don't know which. I looked through all the files it could be and everything seems what you'd expect. Could you tell me what remco looks at in the build? EDIT: I changed the CMD just for testing to `CMD ["./bin/xo-server"]` from an old one I had, but I end up with `ECONNREFUSED`. I assume the remco aspect is required.

Thanks.

**Comment by Ezka77** [comment]
Hi,

first: not at all! Fork it, make a PR if you want to share your ARM version, I'll add the platform along the current one.

second: On start, REMCO read his configuration file, in this repo it's `alpine/remco/config` in the docker container it is in `/etc/remco/config` and create the configuration file for XOA, based on the the template from `alpine/remco/templates/config.toml` and the ENV vars from the Docker container.

For testing, I think you can use docker-compose and the `docker-compose.yml` on ARM, in this file there is some ENV vars required to run XOA. You can add a `command: /bin/sh` (or `ash` ?) to start a shell in the container instead of remco+XOA.

You can run the container with a shell and debug your start process from the command line. I think something like `docker run -it /bin/sh ezka77/xen-orchestra-ce` should start the container and you can inspect your result from there. But to start XOA it will require some more tedious work to start: a Redis server aside, and add to the `docker run` CLI the port number, mount a local directory, set the required ENV vars, log, network etc ...

**Comment by DustyArmstrong** [comment]
Hi Ezka, thanks for replying. 

I was losing my sanity so I ended up with a hybrid version that uses some aspects of your system, but also my own work and then some pulled from other places. Since I'm not using REMCO I can't do a PR, but if I ever have the time to figure it out (and someone else hasn't before me) I'll certainly do a proper fork. 

Dusty.

**Comment by Ezka77** [comment]
Hi @DustyArmstrong 

I've updated the Dockerfile and I'm working on the github CI to build a multi-arch docker. I haven't succeeded yet to push the images as a multi-arch image, but with this Dockerfile you can build the arm64 and arm/v7 version. The build seems to work on CI but ... I've no idea if it run as expected on an ARM :suspect: 

If you have time to build this images and try-it from an ARM let me know if it works.

**Comment by DustyArmstrong** [comment]
Hi, I didn't actually see this until today! 

I'll do my best to give it a test.

**Comment by Ezka77** [comment]
well now you do not need to build it yourself, the build is done along the amd64 version each week ;-) You can use the image from docker hub.
